"""
Contract tests for P1-IMG-1..4 over the public HTTP surface.

The HTTP contract this file protects:
  - The 21-field response shape is unchanged whether the images feature is on
    or off (CLAUDE.md §5.1). No new top-level keys.
  - Feature OFF (tenant not on IMAGE_BINARIES_TENANTS_ALLOWLIST): byte-for-byte
    legacy behaviour — data: URIs stay inline, no contained Binary.
  - Feature ON: `xml` / `bundle_xml` carry contained Binary resources, every
    <img> is `src="#<id>"` with non-empty alt, no data: URIs anywhere in the
    emitted narrative, `fix_log` carries IMG-* audit rows at iteration 0, and
    `source_text` contains no base64 image payload.
  - Same upload twice -> identical Binary ids and payload hashes (CLAUDE.md §4.4).

Uses `tests/fixtures/synthetic_smpc_images.docx` (generated by
`tests/fixtures/gen_synthetic_smpc_images.py`): 4 <img> tags, 3 distinct
images (fig1 == fig4), one without alt text, one TIFF.

Refs: FEATURE_SPEC.md §5 P1-IMG-1..4; CLAUDE.md §5.1, §5.7, §9.1, §9.3.

Run:
    python3 -m unittest tests.contract.test_image_contract -v
"""
from __future__ import annotations

import hashlib
import os
import re
import sys
import unittest

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

_FIXTURE_PATH = os.path.join(_REPO_ROOT, "tests", "fixtures", "synthetic_smpc_images.docx")
_DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
_IMG_TENANT = "img-tenant"
_OTHER_TENANT = "plain-tenant"

# v2.0.0 baseline response shape — frozen public contract (mirrors test_publication.py).
_BASELINE_FIELDS = frozenset({
    "status", "error_count", "warning_count", "info_count", "summary", "iterations",
    "original_xml", "xml", "issues", "fix_log", "validation_log_json",
    "validation_report_md", "fidelity_score", "fidelity_status", "diff_html",
    "bundle_json", "bundle_xml", "source_text", "doc_type", "sections_count", "css_href",
})

_IMG_TAG = re.compile(r"<img\b[^>]*>", re.IGNORECASE)
_CONTAINED_BINARY = re.compile(r"<contained>\s*<Binary>(.*?)</Binary>\s*</contained>", re.DOTALL)


class _ImageContractBase(unittest.TestCase):

    def setUp(self):
        if not os.path.exists(_FIXTURE_PATH):
            self.skipTest(f"fixture not present: {_FIXTURE_PATH} "
                          "(run tests/fixtures/gen_synthetic_smpc_images.py)")
        os.environ["IMAGE_BINARIES_TENANTS_ALLOWLIST"] = _IMG_TENANT
        os.environ.pop("PUBLICATION_TENANTS_ALLOWLIST", None)
        for mod in ("main", "publication_service", "fhir_mapper", "image_embedder"):
            sys.modules.pop(mod, None)
        from fastapi.testclient import TestClient
        import main as main_module
        self.client = TestClient(main_module.app)

    def _post(self, tenant_id: str) -> dict:
        with open(_FIXTURE_PATH, "rb") as fh:
            r = self.client.post(
                "/api/process_stateless",
                files={"file": ("synthetic_smpc_images.docx", fh, _DOCX_MIME)},
                data={"tenant_id": tenant_id},
            )
        if r.status_code == 422:
            self.skipTest("fixture did not pass the SmPC structural gate (P0-2) — regenerate fixture")
        self.assertEqual(r.status_code, 200, r.text[:500])
        return r.json()

    @staticmethod
    def _binaries(xml: str) -> list[dict]:
        out = []
        for m in _CONTAINED_BINARY.finditer(xml):
            body = m.group(1)
            out.append({
                "id": re.search(r'<id value="([^"]+)"', body).group(1),
                "contentType": re.search(r'<contentType value="([^"]+)"', body).group(1),
                "data_sha": hashlib.sha256(re.search(r'<data value="([^"]*)"', body).group(1).encode()).hexdigest(),
            })
        return out


class ResponseShapeTests(_ImageContractBase):

    def test_feature_on_keeps_21_field_shape(self):
        body = self._post(_IMG_TENANT)
        self.assertEqual(set(body.keys()), _BASELINE_FIELDS,
                         "P1-IMG adds NO top-level fields — the manifest lives in the bundle (contained Binary + ext-epi-image-reference)")

    def test_feature_off_keeps_21_field_shape(self):
        body = self._post(_OTHER_TENANT)
        self.assertEqual(set(body.keys()), _BASELINE_FIELDS)


class FeatureOffLegacyTests(_ImageContractBase):
    """Must pass today AND after the change (flag default-off, CLAUDE.md §5.7)."""

    def test_tenant_not_allowlisted_gets_legacy_data_uris(self):
        body = self._post(_OTHER_TENANT)
        self.assertIn("data:image/", body["xml"])
        self.assertNotIn("<contained>", body["xml"])
        self.assertFalse(any(str(f.get("rule", "")).startswith("IMG-") for f in body["fix_log"]))


class FeatureOnTests(_ImageContractBase):

    def test_narrative_images_are_contained_binaries(self):
        body = self._post(_IMG_TENANT)
        for field in ("xml", "bundle_xml"):
            xml = body[field]
            self.assertNotIn("data:image", xml, f"{field}: data: URI leaked into narrative")
            bins = self._binaries(xml)
            self.assertEqual(len(bins), 3, f"{field}: fig1==fig4 dedupes -> 3 Binaries, got {len(bins)}")
            ids = [b["id"] for b in bins]
            self.assertEqual(len(set(ids)), 3, "contained ids unique within the Composition")
            for b in bins:
                self.assertRegex(b["id"], r"^img-[0-9a-f]{32}$")
                self.assertIn(b["contentType"], {"image/png", "image/jpeg", "image/svg+xml"},
                              "only web-safe MIME types after rasterisation")
            self.assertEqual(sum(1 for b in bins if b["contentType"] == "image/png"), 3,
                             "TIFF must have been rasterised to PNG")
            imgs = _IMG_TAG.findall(xml)
            self.assertEqual(len(imgs), 4, f"{field}: 4 <img> tags expected, got {len(imgs)}")
            for tag in imgs:
                attrs = dict(re.findall(r'(\w+)="([^"]*)"', tag))
                self.assertEqual(set(attrs), {"src", "alt"}, tag)
                self.assertIn(attrs["src"].lstrip("#"), ids, f"dangling image ref {attrs['src']}")
                self.assertTrue(attrs["alt"].strip(), f"empty alt on {tag}")
            # Every Binary is declared via the EU imageReference extension, in the same order.
            refs = re.findall(
                r'<extension url="http://ema\.europa\.eu/fhir/StructureDefinition/ext-epi-image-reference">'
                r'\s*<valueReference>\s*<reference value="#([^"]+)"/>', xml)
            self.assertEqual(refs, ids)

    def test_fix_log_has_image_audit_rows_at_iteration_zero(self):
        body = self._post(_IMG_TENANT)
        img_rows = [f for f in body["fix_log"] if str(f.get("rule", "")).startswith("IMG-")]
        by_rule = {}
        for f in img_rows:
            by_rule.setdefault(f["rule"], []).append(f)
        self.assertEqual(len(by_rule.get("IMG-EMBED", [])), 4, by_rule)
        self.assertEqual(len(by_rule.get("IMG-ALT-MISSING", [])), 1, by_rule)
        self.assertEqual(len(by_rule.get("IMG-RASTERISE", [])), 1, by_rule)
        self.assertNotIn("IMG-FORMAT-UNSUPPORTED", by_rule)
        for f in img_rows:
            self.assertEqual(f["iteration"], 0, "mapping-phase actions are logged as iteration 0")
            self.assertEqual(set(f.keys()), {"iteration", "rule", "description", "location"},
                             "same row shape as validator fixes")
            self.assertTrue(f["location"], "location must name the section id")
        # The un-alt'd image sits in section 4.2 of the fixture.
        self.assertEqual(by_rule["IMG-ALT-MISSING"][0]["location"], "4.2")

    def test_source_text_has_no_base64_payload(self):
        body = self._post(_IMG_TENANT)
        self.assertNotIn("data:image", body["source_text"])
        self.assertNotIn(";base64,", body["source_text"])

    def test_original_xml_already_carries_binaries(self):
        # Embedding is a mapping-phase transform: Phase 1 must validate the
        # same Binary-bearing XML that ships (CLAUDE.md §5.3 — no post-hoc rewrite).
        body = self._post(_IMG_TENANT)
        self.assertEqual(len(self._binaries(body["original_xml"])), 3)
        self.assertNotIn("data:image", body["original_xml"])

    def test_same_upload_is_byte_deterministic_for_images(self):
        a = self._binaries(self._post(_IMG_TENANT)["bundle_xml"])
        b = self._binaries(self._post(_IMG_TENANT)["bundle_xml"])
        self.assertEqual(a, b, "Binary ids and payload hashes must not vary run to run")

    def test_fidelity_is_not_degraded_by_images(self):
        # Images contribute zero words to the recall scorer, so the image-bearing
        # fixture must score within rounding of its image-free sibling
        # (CLAUDE.md §5.8 — the reference set never regresses).
        plain_path = os.path.join(_REPO_ROOT, "tests", "fixtures", "synthetic_smpc.docx")
        if not os.path.exists(plain_path):
            self.skipTest("image-free sibling fixture missing")
        with_images = self._post(_IMG_TENANT)
        with open(plain_path, "rb") as fh:
            r = self.client.post("/api/process_stateless",
                                 files={"file": ("synthetic_smpc.docx", fh, _DOCX_MIME)},
                                 data={"tenant_id": _IMG_TENANT})
        self.assertEqual(r.status_code, 200)
        plain = r.json()
        if with_images["fidelity_status"] != "available" or plain["fidelity_status"] != "available":
            self.skipTest("fidelity suppressed by validator errors — not an image concern")
        self.assertAlmostEqual(with_images["fidelity_score"], plain["fidelity_score"], delta=0.5)

if __name__ == "__main__":
    unittest.main()
